os: osx
osx_image: xcode12.2
install:
  - swift package generate-xcodeproj 
jobs:
  include:
    - stage: "Test"
      script: xcodebuild clean test -project StubbornNetwork.xcodeproj -scheme StubbornNetwork-Package 
